image: andreysenov/firebase-tools:latest

deploy:
  script:
    - npm install
    - npm run build
    - firebase deploy --only hosting --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
  only:
    - master